module Main where

import Relude

-- local
import           Data.Format.Wad.Types
import Data.Format.UDMF.Types


main :: IO ()
main = do
    let m = renderUDMFV1_1 twoRooms

    putTextLn m

    let w = newEmptyPWad & addUDMFMap "AMF" m

    putTextLn "Wad"
    print w

    print $ buildWadOD w
    r <- writeWadToFile "amf.wad" w
    print r
    pure ()


emptyMap :: Text
emptyMap = unlines ["// Written by SLADE3", "namespace=\"zdoom\";"]



singleRoom :: UDMFV1_1
singleRoom = UDMF
    [ UDMFComment (CommentSingleLine "Written by Adam")
    , UDMFNS NamespaceZDoom
    , UDMFLineDef newLineDef { _lineDefV1        = DInt32 Nothing 0
                             , _lineDefV2        = DInt32 Nothing 1
                             , _lineDefSideFront = DInt32ND 0
                             , _lineDefBlocking  = Just (DBool (Just True) False)
                             }
    , UDMFLineDef newLineDef { _lineDefV1        = DInt32 Nothing 1
                             , _lineDefV2        = DInt32 Nothing 2
                             , _lineDefBlocking  = Just (DBool (Just True) False)
                             , _lineDefSideFront = DInt32ND 1
                             }
    , UDMFLineDef newLineDef { _lineDefV1        = DInt32 Nothing 2
                             , _lineDefV2        = DInt32 Nothing 3
                             , _lineDefBlocking  = Just (DBool (Just True) False)
                             , _lineDefSideFront = DInt32ND 2
                             }
    , UDMFLineDef newLineDef { _lineDefV1        = DInt32 Nothing 3
                             , _lineDefV2        = DInt32 Nothing 0
                             , _lineDefBlocking  = Just (DBool (Just True) False)
                             , _lineDefSideFront = DInt32ND 3
                             }
    , UDMFSideDef newSideDef { _sideDefTextureMiddle = Just "STONE2", _sideDefSector = DInt32ND 0 }
    , UDMFSideDef newSideDef { _sideDefTextureMiddle = Just "STONE2", _sideDefSector = DInt32ND 0 }
    , UDMFSideDef newSideDef { _sideDefTextureMiddle = Just "STONE2", _sideDefSector = DInt32ND 0 }
    , UDMFSideDef newSideDef { _sideDefTextureMiddle = Just "STONE2", _sideDefSector = DInt32ND 0 }
    , UDMFVertext (newVertex (-256.0, -128.0))
    , UDMFVertext (newVertex (-256.0, 192.0))
    , UDMFVertext (newVertex (64.0, 192.0))
    , UDMFVertext (newVertex (64.0, -128.0))
    , UDMFSector newSector { _sectorHeightCeiling  = Just (DInt32 (Just 128) 0)
                           , _sectorTextureFloor   = DStr "MFLR8_1"
                           , _sectorTextureCeiling = DStr "MFLR8_1"
                           }
    , UDMFThing (newThing (DInt32ND 1)) { _thingX = DDouble (-224.0), _thingY = DDouble (-96.0) }
    ]

twoRooms :: UDMFV1_1
twoRooms = UDMF
    [ UDMFComment (CommentSingleLine "Written by Adam")
    , UDMFComment (CommentMultiLine "test line1\ntest line 2\ntest line 3\n\n")
    , UDMFNS NamespaceZDoom

    , UDMFLineDef newLineDef { _lineDefV1        = DInt32 Nothing 0
                             , _lineDefV2        = DInt32 Nothing 1
                             , _lineDefSideFront = DInt32ND 0
                             , _lineDefBlocking  = Just (DBool (Just True) False)
                             }
    , UDMFLineDef newLineDef { _lineDefV1        = DInt32 Nothing 1
                             , _lineDefV2        = DInt32 Nothing 2
                             , _lineDefBlocking  = Just (DBool (Just True) False)
                             , _lineDefSideFront = DInt32ND 1
                             }
    , UDMFLineDef newLineDef { _lineDefV1        = DInt32 Nothing 2
                             , _lineDefV2        = DInt32 Nothing 3
                             , _lineDefBlocking  = Just (DBool (Just True) False)
                             , _lineDefSideFront = DInt32ND 2
                             }
    , UDMFLineDef newLineDef { _lineDefV1        = DInt32 Nothing 3
                             , _lineDefV2        = DInt32 Nothing 0
                             , _lineDefBlocking  = Just (DBool (Just True) False)
                             , _lineDefSideFront = DInt32ND 3
                             }
    , UDMFSideDef newSideDef { _sideDefTextureMiddle = Just "STONE2", _sideDefSector = DInt32ND 0 }
    , UDMFSideDef newSideDef { _sideDefTextureMiddle = Just "STONE2", _sideDefSector = DInt32ND 0 }
    , UDMFSideDef newSideDef { _sideDefTextureMiddle = Just "STONE2", _sideDefSector = DInt32ND 0 }
    , UDMFSideDef newSideDef { _sideDefTextureMiddle = Just "STONE2", _sideDefSector = DInt32ND 0 }
    , UDMFVertext (newVertex (-384.0, 32.0))
    , UDMFVertext (newVertex (-384.0, 224.0))
    , UDMFVertext (newVertex (-128.0, 224.0))
    , UDMFVertext (newVertex (-128.0, 32))
    , UDMFSector newSector { _sectorHeightCeiling  = Just (DInt32 (Just 128) 0)
                           , _sectorTextureFloor   = DStr "MFLR8_1"
                           , _sectorTextureCeiling = DStr "MFLR8_1"
                           }
    , UDMFThing (newThing (DInt32ND 1)) { _thingX = DDouble (-260.0), _thingY = DDouble (128.0) }


    , UDMFLineDef newLineDef { _lineDefV1        = DInt32 Nothing 4
                             , _lineDefV2        = DInt32 Nothing 5
                             , _lineDefSideFront = DInt32ND 4
                             , _lineDefBlocking  = Just (DBool (Just True) False)
                             }
    , UDMFLineDef newLineDef { _lineDefV1        = DInt32 Nothing 5
                             , _lineDefV2        = DInt32 Nothing 6
                             , _lineDefBlocking  = Just (DBool (Just True) False)
                             , _lineDefSideFront = DInt32ND 5
                             }
    , UDMFLineDef newLineDef { _lineDefV1        = DInt32 Nothing 6
                             , _lineDefV2        = DInt32 Nothing 7
                             , _lineDefBlocking  = Just (DBool (Just True) False)
                             , _lineDefSideFront = DInt32ND 6
                             }
    , UDMFLineDef newLineDef { _lineDefV1        = DInt32 Nothing 7
                             , _lineDefV2        = DInt32 Nothing 4
                             , _lineDefBlocking  = Just (DBool (Just True) False)
                             , _lineDefSideFront = DInt32ND 7
                             }
    , UDMFSideDef newSideDef {
         _sideDefTextureMiddle = Just "STONE3", _sideDefSector = DInt32ND 1 }
    , UDMFSideDef newSideDef { _sideDefTextureMiddle = Just "STONE3", _sideDefSector = DInt32ND 1 }
    , UDMFSideDef newSideDef { _sideDefTextureMiddle = Just "STONE3", _sideDefSector = DInt32ND 1 }
    , UDMFSideDef newSideDef { _sideDefTextureMiddle = Just "STONE3", _sideDefSector = DInt32ND 1 }
    , UDMFVertext (newVertex (0, -96))
    , UDMFVertext (newVertex (0, 96))
    , UDMFVertext (newVertex (320, 96))
    , UDMFVertext (newVertex (320, -96))
    , UDMFSector newSector { _sectorHeightCeiling  = Just (DInt32 (Just 128) 0)
                           , _sectorTextureFloor   = DStr "MFLR8_1"
                           , _sectorTextureCeiling = DStr "MFLR8_1"
                           }

    ]





exMap :: Text
exMap = unlines
    [ "namespace = \"zdoom\";"
    , "thing"
    , "{"
    , "x = -288.000;"
    , "y = -92.000;"
    , "type = 1;"
    , "coop = true;"
    , "dm = true;"
    , "single = true;"
    , "skill1 = true;"
    , "skill2 = true;"
    , "skill3 = true;"
    , "skill4 = true;"
    , "skill5 = true;"
    , "}"
    , ""
    , "thing"
    , "{"
    , "x = 244.000;"
    , "y = 248.000;"
    , "type = 14;"
    , "coop = true;"
    , "dm = true;"
    , "single = true;"
    , "skill1 = true;"
    , "skill2 = true;"
    , "skill3 = true;"
    , "skill4 = true;"
    , "skill5 = true;"
    , "id = 66;"
    , "}"
    , ""
    , "thing"
    , "{"
    , "x = -248.000;"
    , "y = 36.000;"
    , "type = 14;"
    , "coop = true;"
    , "dm = true;"
    , "single = true;"
    , "skill1 = true;"
    , "skill2 = true;"
    , "skill3 = true;"
    , "skill4 = true;"
    , "skill5 = true;"
    , "id = 99;"
    , "}"
    , ""
    , "thing"
    , "{"
    , "x = -164.000;"
    , "y = -24.000;"
    , "type = 48;"
    , "coop = true;"
    , "dm = true;"
    , "single = true;"
    , "skill1 = true;"
    , "skill2 = true;"
    , "skill3 = true;"
    , "skill4 = true;"
    , "skill5 = true;"
    , "}"
    , ""
    , "vertex"
    , "{"
    , "x = -320.000;"
    , "y = 128.000;"
    , "}"
    , ""
    , "vertex"
    , "{"
    , "x = 0.000;"
    , "y = 128.000;"
    , "}"
    , ""
    , "vertex"
    , "{"
    , "x = 0.000;"
    , "y = 64.000;"
    , "}"
    , ""
    , "vertex"
    , "{"
    , "x = 0.000;"
    , "y = -128.000;"
    , "}"
    , ""
    , "vertex"
    , "{"
    , "x = -320.000;"
    , "y = -128.000;"
    , "}"
    , ""
    , "vertex"
    , "{"
    , "x = 0.000;"
    , "y = -64.000;"
    , "}"
    , ""
    , "vertex"
    , "{"
    , "x = 320.000;"
    , "y = 64.000;"
    , "}"
    , ""
    , "vertex"
    , "{"
    , "x = 320.000;"
    , "y = 32.000;"
    , "}"
    , ""
    , "vertex"
    , "{"
    , "x = 320.000;"
    , "y = -64.000;"
    , "}"
    , ""
    , "vertex"
    , "{"
    , "x = 48.000;"
    , "y = 180.000;"
    , "}"
    , ""
    , "vertex"
    , "{"
    , "x = 48.000;"
    , "y = 300.000;"
    , "}"
    , ""
    , "vertex"
    , "{"
    , "x = 324.000;"
    , "y = 300.000;"
    , "}"
    , ""
    , "vertex"
    , "{"
    , "x = 324.000;"
    , "y = 180.000;"
    , "}"
    , ""
    , "vertex"
    , "{"
    , "x = -40.000;"
    , "y = 36.000;"
    , "}"
    , ""
    , "vertex"
    , "{"
    , "x = -40.000;"
    , "y = 100.000;"
    , "}"
    , ""
    , "vertex"
    , "{"
    , "x = -104.000;"
    , "y = 100.000;"
    , "}"
    , ""
    , "vertex"
    , "{"
    , "x = -104.000;"
    , "y = 36.000;"
    , "}"
    , ""
    , "vertex"
    , "{"
    , "x = 320.000;"
    , "y = -16.000;"
    , "}"
    , ""
    , "vertex"
    , "{"
    , "x = 156.000;"
    , "y = 272.000;"
    , "}"
    , ""
    , "vertex"
    , "{"
    , "x = 92.000;"
    , "y = 272.000;"
    , "}"
    , ""
    , "vertex"
    , "{"
    , "x = 156.000;"
    , "y = 208.000;"
    , "}"
    , ""
    , "vertex"
    , "{"
    , "x = 92.000;"
    , "y = 208.000;"
    , "}"
    , ""
    , "linedef"
    , "{"
    , "v1 = 0;"
    , "v2 = 1;"
    , "sidefront = 0;"
    , "blocking = true;"
    , "}"
    , ""
    , "linedef"
    , "{"
    , "v1 = 1;"
    , "v2 = 2;"
    , "sidefront = 1;"
    , "blocking = true;"
    , "}"
    , ""
    , "linedef"
    , "{"
    , "v1 = 3;"
    , "v2 = 4;"
    , "sidefront = 2;"
    , "blocking = true;"
    , "}"
    , ""
    , "linedef"
    , "{"
    , "v1 = 4;"
    , "v2 = 0;"
    , "sidefront = 3;"
    , "blocking = true;"
    , "}"
    , ""
    , "linedef"
    , "{"
    , "v1 = 2;"
    , "v2 = 5;"
    , "sidefront = 4;"
    , "sideback = 9;"
    , "twosided = true;"
    , "}"
    , ""
    , "linedef"
    , "{"
    , "v1 = 5;"
    , "v2 = 3;"
    , "sidefront = 5;"
    , "blocking = true;"
    , "}"
    , ""
    , "linedef"
    , "{"
    , "v1 = 2;"
    , "v2 = 6;"
    , "sidefront = 6;"
    , "blocking = true;"
    , "}"
    , ""
    , "linedef"
    , "{"
    , "v1 = 6;"
    , "v2 = 7;"
    , "sidefront = 7;"
    , "special = 243;"
    , "blocking = true;"
    , "playeruse = true;"
    , "}"
    , ""
    , "linedef"
    , "{"
    , "v1 = 8;"
    , "v2 = 5;"
    , "sidefront = 8;"
    , "blocking = true;"
    , "}"
    , ""
    , "linedef"
    , "{"
    , "v1 = 9;"
    , "v2 = 10;"
    , "sidefront = 10;"
    , "blocking = true;"
    , "}"
    , ""
    , "linedef"
    , "{"
    , "v1 = 10;"
    , "v2 = 11;"
    , "sidefront = 11;"
    , "blocking = true;"
    , "}"
    , ""
    , "linedef"
    , "{"
    , "v1 = 11;"
    , "v2 = 12;"
    , "sidefront = 12;"
    , "blocking = true;"
    , "}"
    , ""
    , "linedef"
    , "{"
    , "v1 = 12;"
    , "v2 = 9;"
    , "sidefront = 13;"
    , "blocking = true;"
    , "}"
    , ""
    , "linedef"
    , "{"
    , "v1 = 13;"
    , "v2 = 14;"
    , "sidefront = 18;"
    , "sideback = 14;"
    , "special = 70;"
    , "twosided = true;"
    , "arg0 = 66;"
    , "repeatspecial = true;"
    , "arg1 = 33;"
    , "playercross = true;"
    , "}"
    , ""
    , "linedef"
    , "{"
    , "v1 = 15;"
    , "v2 = 14;"
    , "sidefront = 15;"
    , "sideback = 21;"
    , "special = 70;"
    , "twosided = true;"
    , "arg0 = 66;"
    , "repeatspecial = true;"
    , "arg1 = 33;"
    , "playercross = true;"
    , "}"
    , ""
    , "linedef"
    , "{"
    , "v1 = 15;"
    , "v2 = 16;"
    , "sidefront = 20;"
    , "sideback = 16;"
    , "special = 70;"
    , "twosided = true;"
    , "arg0 = 66;"
    , "repeatspecial = true;"
    , "arg1 = 33;"
    , "playercross = true;"
    , "}"
    , ""
    , "linedef"
    , "{"
    , "v1 = 16;"
    , "v2 = 13;"
    , "sidefront = 19;"
    , "sideback = 17;"
    , "special = 70;"
    , "twosided = true;"
    , "arg0 = 66;"
    , "repeatspecial = true;"
    , "arg1 = 33;"
    , "playercross = true;"
    , "}"
    , ""
    , "linedef"
    , "{"
    , "v1 = 7;"
    , "v2 = 17;"
    , "sidefront = 22;"
    , "special = 243;"
    , "blocking = true;"
    , "playeruse = true;"
    , "}"
    , ""
    , "linedef"
    , "{"
    , "v1 = 17;"
    , "v2 = 8;"
    , "sidefront = 23;"
    , "special = 243;"
    , "blocking = true;"
    , "playeruse = true;"
    , "}"
    , ""
    , "linedef"
    , "{"
    , "v1 = 18;"
    , "v2 = 19;"
    , "sidefront = 25;"
    , "sideback = 24;"
    , "special = 70;"
    , "twosided = true;"
    , "arg0 = 99;"
    , "repeatspecial = true;"
    , "arg1 = 77;"
    , "playercross = true;"
    , "}"
    , ""
    , "linedef"
    , "{"
    , "v1 = 20;"
    , "v2 = 18;"
    , "sidefront = 27;"
    , "sideback = 26;"
    , "special = 70;"
    , "twosided = true;"
    , "arg0 = 99;"
    , "repeatspecial = true;"
    , "arg1 = 77;"
    , "playercross = true;"
    , "}"
    , ""
    , "linedef"
    , "{"
    , "v1 = 21;"
    , "v2 = 20;"
    , "sidefront = 29;"
    , "sideback = 28;"
    , "special = 70;"
    , "twosided = true;"
    , "arg0 = 99;"
    , "repeatspecial = true;"
    , "arg1 = 77;"
    , "playercross = true;"
    , "}"
    , ""
    , "linedef"
    , "{"
    , "v1 = 19;"
    , "v2 = 21;"
    , "sidefront = 31;"
    , "sideback = 30;"
    , "special = 70;"
    , "twosided = true;"
    , "arg0 = 99;"
    , "repeatspecial = true;"
    , "arg1 = 77;"
    , "playercross = true;"
    , "}"
    , ""
    , "sidedef"
    , "{"
    , "sector = 0;"
    , "texturemiddle = \"STONE2\";"
    , "}"
    , ""
    , "sidedef"
    , "{"
    , "sector = 0;"
    , "texturemiddle = \"STONE2\";"
    , "}"
    , ""
    , "sidedef"
    , "{"
    , "sector = 0;"
    , "texturemiddle = \"STONE2\";"
    , "}"
    , ""
    , "sidedef"
    , "{"
    , "sector = 0;"
    , "texturemiddle = \"STONE2\";"
    , "}"
    , ""
    , "sidedef"
    , "{"
    , "sector = 0;"
    , "offsetx = 64;"
    , "}"
    , ""
    , "sidedef"
    , "{"
    , "sector = 0;"
    , "texturemiddle = \"STONE2\";"
    , "offsetx = 192;"
    , "}"
    , ""
    , "sidedef"
    , "{"
    , "sector = 1;"
    , "texturemiddle = \"STONE2\";"
    , "}"
    , ""
    , "sidedef"
    , "{"
    , "sector = 1;"
    , "texturemiddle = \"SW1EXIT\";"
    , "}"
    , ""
    , "sidedef"
    , "{"
    , "sector = 1;"
    , "texturemiddle = \"STONE2\";"
    , "}"
    , ""
    , "sidedef"
    , "{"
    , "sector = 1;"
    , "}"
    , ""
    , "sidedef"
    , "{"
    , "sector = 2;"
    , "texturemiddle = \"STONE2\";"
    , "}"
    , ""
    , "sidedef"
    , "{"
    , "sector = 2;"
    , "texturemiddle = \"STONE2\";"
    , "}"
    , ""
    , "sidedef"
    , "{"
    , "sector = 2;"
    , "texturemiddle = \"STONE2\";"
    , "}"
    , ""
    , "sidedef"
    , "{"
    , "sector = 2;"
    , "texturemiddle = \"STONE2\";"
    , "}"
    , ""
    , "sidedef"
    , "{"
    , "sector = 3;"
    , "}"
    , ""
    , "sidedef"
    , "{"
    , "sector = 3;"
    , "}"
    , ""
    , "sidedef"
    , "{"
    , "sector = 3;"
    , "}"
    , ""
    , "sidedef"
    , "{"
    , "sector = 3;"
    , "}"
    , ""
    , "sidedef"
    , "{"
    , "sector = 0;"
    , "texturebottom = \"BFALL1\";"
    , "}"
    , ""
    , "sidedef"
    , "{"
    , "sector = 0;"
    , "texturebottom = \"BFALL1\";"
    , "}"
    , ""
    , "sidedef"
    , "{"
    , "sector = 0;"
    , "texturebottom = \"BFALL1\";"
    , "}"
    , ""
    , "sidedef"
    , "{"
    , "sector = 0;"
    , "texturebottom = \"BFALL1\";"
    , "}"
    , ""
    , "sidedef"
    , "{"
    , "sector = 1;"
    , "texturemiddle = \"SW1EXIT\";"
    , "}"
    , ""
    , "sidedef"
    , "{"
    , "sector = 1;"
    , "texturemiddle = \"SW1EXIT\";"
    , "offsetx = 80;"
    , "}"
    , ""
    , "sidedef"
    , "{"
    , "sector = 4;"
    , "}"
    , ""
    , "sidedef"
    , "{"
    , "sector = 2;"
    , "texturebottom = \"BFALL1\";"
    , "}"
    , ""
    , "sidedef"
    , "{"
    , "sector = 4;"
    , "}"
    , ""
    , "sidedef"
    , "{"
    , "sector = 2;"
    , "texturebottom = \"BFALL1\";"
    , "}"
    , ""
    , "sidedef"
    , "{"
    , "sector = 4;"
    , "}"
    , ""
    , "sidedef"
    , "{"
    , "sector = 2;"
    , "texturebottom = \"BFALL1\";"
    , "}"
    , ""
    , "sidedef"
    , "{"
    , "sector = 4;"
    , "}"
    , ""
    , "sidedef"
    , "{"
    , "sector = 2;"
    , "texturebottom = \"BFALL1\";"
    , "}"
    , ""
    , "sector"
    , "{"
    , "texturefloor = \"MFLR8_1\";"
    , "textureceiling = \"MFLR8_1\";"
    , "heightceiling = 128;"
    , "id = 77;"
    , "}"
    , ""
    , "sector"
    , "{"
    , "texturefloor = \"MFLR8_1\";"
    , "textureceiling = \"MFLR8_1\";"
    , "heightceiling = 128;"
    , "}"
    , ""
    , "sector"
    , "{"
    , "texturefloor = \"MFLR8_1\";"
    , "textureceiling = \"MFLR8_1\";"
    , "heightceiling = 128;"
    , "id = 33;"
    , "gravity = 0.100000;"
    , "}"
    , ""
    , "sector"
    , "{"
    , "texturefloor = \"GATE4\";"
    , "textureceiling = \"GATE4\";"
    , "heightfloor = 8;"
    , "heightceiling = 120;"
    , "ypanningceiling = 32.000000;"
    , "ypanningfloor = 104.000000;"
    , "xpanningceiling = 8.000000;"
    , "}"
    , ""
    , "sector"
    , "{"
    , "texturefloor = \"GATE4\";"
    , "textureceiling = \"GATE4\";"
    , "heightfloor = 8;"
    , "heightceiling = 120;"
    , "ypanningceiling = 32.000000;"
    , "ypanningfloor = 104.000000;"
    , "xpanningceiling = 8.000000;"
    , "}"
    , ""
    ]
